//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sContable.DAL
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Asiento_Contable
    {
        public int Cod { get; set; }
        public int Nro_folio { get; set; }
        public string detalle { get; set; }
        public Nullable<decimal> debitos { get; set; }
        public Nullable<decimal> creditos { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_Comprobante { get; set; }
        public Nullable<int> id_Libro_Diario { get; set; }
        public Nullable<int> id_TiposdeAsientos { get; set; }
        public Nullable<int> id_PlanDeCuentas { get; set; }
    
        [JsonIgnore]
        public virtual Comprobante Comprobante { get; set; }
        [JsonIgnore]
        public virtual Libro_Diario Libro_Diario { get; set; }
        [JsonIgnore]
        public virtual Plan_Cuenta Plan_Cuenta { get; set; }
        [JsonIgnore]
        public virtual Tipo_Asientos Tipo_Asientos { get; set; }
    }
}
