//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sContable.DAL
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        public int nro { get; set; }
        public System.DateTime fecha_Emision { get; set; }
        public Nullable<decimal> cifra { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> id_Banco { get; set; }
    
        [JsonIgnore]
        public virtual Banco Banco { get; set; }
    }
}
