//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sContable.DAL
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comprobante()
        {
            this.Asiento_Contable = new HashSet<Asiento_Contable>();
        }
    
        public int Nro { get; set; }
        public System.DateTime fecha { get; set; }
        public string concepto { get; set; }
        public string estado { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> debitos { get; set; }
        public Nullable<decimal> creditos { get; set; }
        public Nullable<int> id_tipodecomprobante { get; set; }
        public Nullable<int> id_cuenta { get; set; }
        public Nullable<int> id_Moneda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Asiento_Contable> Asiento_Contable { get; set; }
        [JsonIgnore]
        public virtual Cuenta Cuenta { get; set; }
        [JsonIgnore]
        public virtual Moneda Moneda { get; set; }
        [JsonIgnore]
        public virtual Tipo_Comprobante Tipo_Comprobante { get; set; }
    }
}
