//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sContable.DAL
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuenta()
        {
            this.Comprobantes = new HashSet<Comprobante>();
            this.Cuenta1 = new HashSet<Cuenta>();
        }
    
        public int id { get; set; }
        public string Cod { get; set; }
        public string nombre { get; set; }
        public Nullable<int> cta_padre { get; set; }
        public Nullable<int> id_PlanDeCuentas { get; set; }
        public Nullable<int> id_Banco { get; set; }
        public Nullable<int> id_Moneda { get; set; }
    
        [JsonIgnore]
        public virtual Banco Banco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Comprobante> Comprobantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Cuenta> Cuenta1 { get; set; }
        [JsonIgnore]
        public virtual Cuenta Cuenta2 { get; set; }
        [JsonIgnore]
        public virtual Moneda Moneda { get; set; }
        [JsonIgnore]
        public virtual Plan_Cuenta Plan_Cuenta { get; set; }
    }
}
