//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sContable.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sContableEntities : DbContext
    {
        public sContableEntities()
            : base("name=sContableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asiento_Contable> Asiento_Contable { get; set; }
        public virtual DbSet<Banco> Bancoes { get; set; }
        public virtual DbSet<Centro_Costos> Centro_Costos { get; set; }
        public virtual DbSet<Cheque> Cheques { get; set; }
        public virtual DbSet<Comprobante> Comprobantes { get; set; }
        public virtual DbSet<Cuenta> Cuentas { get; set; }
        public virtual DbSet<Departamento> Departamentoes { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<Libro_Diario> Libro_Diario { get; set; }
        public virtual DbSet<Moneda> Monedas { get; set; }
        public virtual DbSet<Plan_Cuenta> Plan_Cuenta { get; set; }
        public virtual DbSet<Tipo_Asientos> Tipo_Asientos { get; set; }
        public virtual DbSet<Tipo_Cambio> Tipo_Cambio { get; set; }
        public virtual DbSet<Tipo_Comprobante> Tipo_Comprobante { get; set; }
    }
}
